# Generated by Django 5.0.4 on 2024-04-16 18:56

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('category_ru', models.CharField(max_length=100, null=True)),
                ('category_en', models.CharField(max_length=100, null=True)),
                ('category_ky', models.CharField(max_length=100, null=True)),
                ('marka', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ky', models.CharField(max_length=100, null=True)),
                ('price', models.PositiveIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('city_ru', models.CharField(max_length=100, null=True)),
                ('city_en', models.CharField(max_length=100, null=True)),
                ('city_ky', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('country_ru', models.CharField(max_length=100, null=True)),
                ('country_en', models.CharField(max_length=100, null=True)),
                ('country_ky', models.CharField(max_length=100, null=True)),
                ('with_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('color', models.CharField(max_length=100)),
                ('color_ru', models.CharField(max_length=100, null=True)),
                ('color_en', models.CharField(max_length=100, null=True)),
                ('color_ky', models.CharField(max_length=100, null=True)),
                ('volume', models.FloatField()),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('total_number', models.IntegerField()),
                ('buy_now', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auction.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.customuser')),
            ],
        ),
    ]
