# Generated by Django 5.0.4 on 2024-04-16 14:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('category_ru', models.CharField(max_length=100, null=True)),
                ('category_en', models.CharField(max_length=100, null=True)),
                ('category_ky', models.CharField(max_length=100, null=True)),
                ('marka', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ky', models.CharField(max_length=100, null=True)),
                ('price', models.PositiveIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('city_ru', models.CharField(max_length=100, null=True)),
                ('city_en', models.CharField(max_length=100, null=True)),
                ('city_ky', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('country_ru', models.CharField(max_length=100, null=True)),
                ('country_en', models.CharField(max_length=100, null=True)),
                ('country_ky', models.CharField(max_length=100, null=True)),
                ('with_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('color', models.CharField(max_length=100)),
                ('color_ru', models.CharField(max_length=100, null=True)),
                ('color_en', models.CharField(max_length=100, null=True)),
                ('color_ky', models.CharField(max_length=100, null=True)),
                ('volume', models.FloatField()),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('total_number', models.IntegerField()),
                ('buy_now', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auction.car')),
            ],
        ),
    ]
